### ISSUE TITLE
Spartanization Bug - Unnecessary Removal Of 0 Subtraction That Does Nothing 

### ISSUE THREAD

**Issue by dngreenst** [SpartanRefactoring/spartan-refactoring#113]
In DeclarationInitializerReturnAssignment, line 50:

3 spartanization suggestions to remove subtraction of 0. Only one actual suggestion in the file:

 
<img width="602" alt="spartanizationbug2_3" src="https://cloud.githubusercontent.com/assets/20325207/18224220/2c05e3dc-71d7-11e6-91d7-f3b51ca68741.png">

<img width="916" alt="spartanizationbug2_2" src="https://cloud.githubusercontent.com/assets/20325207/18224223/3ed0a218-71d7-11e6-93f5-533dcbb0ff9c.png">

There is no subtraction of 0, and trying to spartanize does not do anything.

<img width="960" alt="spartanizationbug2_1" src="https://cloud.githubusercontent.com/assets/20325207/18224226/5573f678-71d7-11e6-930c-8e66104ed4a4.png">

**Comment by yossigil** [comment]
@dormaayan : I think this is something small  you did not remember. Please insert a test case, and work on fixing it.

**Comment by dormaayan** [comment]
@yossigil  , @dngreenst  : 
I corrected the bug and now it doesn't offer spartanization in that case.
But 2 tests of that issue aren't pass right now, I think that's because it reads only the left infix expression in the entire expression,
Are you sure the wring should handle such cases ?

**Comment by yossigil** [comment]
I fixed this. It now works in all cases. Please look at the code. It is as simple as it can be.

**Comment by dormaayan** [comment]
@yossigil  : Look at this 2 tests, they are still fail and thats what  I talked about in my previous response, your changes didnt solved that :

<img width="437" alt="fail" src="https://cloud.githubusercontent.com/assets/19957447/18227248/826f6438-7226-11e6-96a8-8e4acfbdcc53.png">

I think thats a tricky case and Im not sure if we need to support that...
What do you think ?

**Comment by yossigil** [comment]
I fixed everything. It was just a matter of thinking about the MINUS as a list, whose length is at least 2.
Check out the code, with this perspective, there are fewer cases to consider.

**Comment by dormaayan** [comment]
@yossigil  : I remove those tests if they are irrelevant
